pipeline:

  install_history_server_bucket_secrets:
    image: banzaicloud/ci-pipeline-client:0.10
    action: InstallSecret
    clusterSecret:
      # sourceSecretName:
      name: '{{ .CICD_REPO_NAME }}-hs-bucket'
      namespace: default
      merge: true
      convertToPreferredFormat: true
      spec: []

  install_history_server_auth_secrets:
    image: banzaicloud/ci-pipeline-client:0.10
    action: InstallSecret
    clusterSecret:
      # sourceSecretName:
      name: '{{ .CICD_REPO_NAME }}-hs-auth'
      namespace: default
      merge: true
      spec:
        - name: htpasswd
          source: htpasswd

  install_zeppelin_auth_secrets:
    image: banzaicloud/ci-pipeline-client:0.10
    action: InstallSecret
    clusterSecret:
      # sourceSecretName:
      name: '{{ .CICD_REPO_NAME }}-zeppelin-auth'
      namespace: default
      merge: true
      spec: []

  package_application:
    image: lachlanevenson/k8s-helm:latest
    commands:
      - helm init -c
      - helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
      - helm package -u ./.banzaicloud/charts/spotguide-zeppelin

  deploy_application:
    image: banzaicloud/ci-pipeline-client:0.10
    action: EnsureDeployment
    deployment:
      name: './spotguide-zeppelin-1.0.0.tgz'
      releaseName: '{{ .CICD_REPO_NAME }}'
      values:
        banzaicloud:
          secret:
            historyServer:
            zeppelin:
        historyServer:
          enabled:
        zeppelin-spark:
          zeppelin:
            userCredentialSecretName: '{{ .CICD_REPO_NAME }}-zeppelin-auth'
            sparkEventLogStorage:
              secretName: '{{ .CICD_REPO_NAME }}-hs-bucket'
            ingress:
              enabled: true
              baseUrl:
              annotations:
                kubernetes.io/ingress.class: traefik
                traefik.frontend.rule.type: PathPrefixStrip
                ingress.kubernetes.io/ssl-redirect: 'true'
              hosts:
                - 'zeppelin-{{ printf "%s-%s" .CICD_REPO_NAME .CLUSTER_NAME | sha1sum | trunc 10}}.{{.ORG_NAME}}.{{.DOMAIN_NAME}}'
          spark:
            monitoring:
              enabled:
              jmxCollector:
              metricsProperties:
            spark-hs:
              sparkEventLogStorage:
                secretName: '{{ .CICD_REPO_NAME }}-hs-bucket'
              ingress:
                enabled: true
                annotations:
                  kubernetes.io/ingress.class: traefik
                  traefik.ingress.kubernetes.io/auth-secret: '{{ .CICD_REPO_NAME }}-hs-auth'
                  traefik.frontend.rule.type: PathPrefixStrip
                  traefik.ingress.kubernetes.io/auth-type: basic
                  ingress.kubernetes.io/ssl-redirect: 'true'
                hosts:
                  - 'shs-{{ printf "%s-%s" .CICD_REPO_NAME .CLUSTER_NAME | sha1sum | trunc 10}}.{{.ORG_NAME}}.{{.DOMAIN_NAME}}'
